telegram_project/panel/urls.py
from django.conf import settings
from django.urls import path, include
from . import views
from .views import TelegramsListView, TelegramDetailView, TelegramsDeleteView, TelegramsUpdateView, CheckUnits, TelegramsSearchView, TelegramsArchive
urlpatterns = [

    path('', TelegramsListView.as_view(), name="panel-home"),
    path('add_tlg/', views.add_tlg, name='add-tlg'),
    path('telegram/<int:pk>/', TelegramDetailView.as_view(), name='telegram-detail'),
    path('delete/<int:pk>/', TelegramsDeleteView.as_view(), name='telegram-delete'),
    path('update/<int:pk>/', TelegramsUpdateView.as_view(), name='telegram-update'),
    path('check/<int:pk>/', CheckUnits, name='check'),
    #path('pdf_view/<int:pk>/', views.pdf_view,document_root=settings.MEDIA_ROOT,  name='pdf-view'),
    path('unit_detail/<str:name>/', views.search_by_unit, name='unit-detail'),
    path('search/', TelegramsSearchView.as_view(), name='search-telegrams'),
    path('archive/', TelegramsArchive.as_view(), name='archive-telegrams'),

]

telegram_project/telegram_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include("panel.urls")),
    path('control_up/', include('calendarcontrol.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='telegram_project/login.html', redirect_authenticated_user=True), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.index, name='index')

]

handler404 = 'telegram_project.views.error_404_view'
handler403 = 'telegram_project.views.error_403_view'

telegram_project/panel/models.py
import uuid
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import date
from django.core.validators import FileExtensionValidator
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver


# Create your models here.


def user_directory_path(instance, filename):
    current_day = date.today()
    ext = filename.split('.')[-1]
    filename = f"{str(uuid.uuid4().hex)}.{ext}"
    return f'tlg_dir/{instance.author_id}/{current_day.year}/{current_day.month}/{filename}'


class Telegrams(models.Model):
    priority_ = [('1', 'Висока'), ('0', 'Низька')]
    date_create = models.DateTimeField(default=timezone.now)
    description = models.TextField(verbose_name= 'Опис телеграми')
    deadline = models.DateTimeField(default=timezone.now, verbose_name='Виконати до')
    tlg_scan = models.FileField(upload_to=user_directory_path, null=True, blank=True,
                                validators=[FileExtensionValidator(allowed_extensions=['pdf'])],
                                verbose_name='Завантажити скан-копію телеграми')
    tlg_number = models.CharField(max_length=100, null=True, verbose_name='Номер вихідної телеграми')
    note = models.CharField(max_length=5000, null=True, blank=True, verbose_name='Примітки')
    confirm = models.BooleanField(default=False, verbose_name='Телеграма виконана!')
    priority = models.CharField(max_length=20, choices=priority_, blank=False, verbose_name='Важливість телеграми', default='0')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

    def get_id(self):
        return str(self.id)

    def replace_tlg_pdf(self):
        return str(self.tlg_scan)


class Executors(models.Model):
    unit = models.CharField(max_length=100)
    status = models.BooleanField(default=False)
    telegrams = models.ForeignKey(Telegrams, on_delete=models.CASCADE)


@receiver(pre_delete, sender=Telegrams)
def Telegrams_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.tlg_scan.delete(False)

telegram_project/panel/forms.py
from django import forms
from .models import Telegrams


class AddTelegram(forms.ModelForm):
    units = [('ALL', 'Виділити всі'), ('A2326', 'A2326'), ('A0355', 'A0355'), ('A1214', 'A1214'),
             ('A0501', 'A0501'), ('A0536', 'A0536'), ('A0693', 'A0693'), ('A1302', 'A1302'), ('A3283', 'A3283'),
             ('A1978', 'A1978'),
             ('A1962', 'A1962'), ('A0563', 'A0563'), ('A1964', 'A1964'), ('A0389', 'A0389'), ('A0591', 'A0591'),
             ('A3336', 'A3336'), ('A1828', 'A1828'),
             ('A3034', 'A3034'), ('A1035', 'A1035'), ('A0943', 'A0943'), ('A1823', 'A1823'), ('A0891', 'A0891'),
             ('A2129', 'A2129'), ('A3139', 'A3139'),
             ('A3750', 'A3750'), ('A1363', 'A1363'), ('A1588', 'A1588'), ('A1361', 'A1361'),
             ('Дн ОТЦК та СП', 'Дн ОТЦК та СП'),
             ('Дон ОТЦК та СП', 'Дон ОТЦК та СП'), ('Зп ОТЦК та СП', 'Зп ОТЦК та СП'),
             ('Хар ОТЦК та СП', 'Хар ОТЦК та СП'), ('Луг ОТЦК та СП', 'Луг  ОТЦК та СП'),
             ('A4226', 'A4226'), ('64 ПУСЗ та ІС', '64 ПУСЗ та ІС'),
             ]
    executors = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=units, label="Розрахунок розсилки")

    class Meta:
        model = Telegrams
        fields = ('deadline', 'description', 'tlg_scan', 'tlg_number', 'note', 'priority')


class SearchTelegrams(forms.Form):
    search_input = forms.CharField(max_length=100, required=False, label="Номер телеграми")
    confirm = forms.ChoiceField(widget=forms.CheckboxSelectMultiple, choices=[('1', 'Так')], required=False, label="Статус телеграми (виконана/невиконана)")
    priority = forms.ChoiceField(widget=forms.RadioSelect, choices=[('0', 'Низька'), ('1', 'Висока')], required=False, label="Пріорітет телеграми")
    date_create = forms.CharField(max_length=30, required=False, label="Дата створення")

telegram_project/panel/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, FileResponse, Http404, HttpResponse, response
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from .models import Telegrams, Executors
from .forms import AddTelegram, SearchTelegrams
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, FormView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib import messages
from django.db.models import Q
import os


# Create your views here.


# def index(request):
#     return render(request, 'panel/index.html')


class TelegramsListView(LoginRequiredMixin, ListView):
    model = Telegrams
    template_name = 'panel/index.html'
    paginate_by = 10

    def get_queryset(self):
        return Telegrams.objects.all().filter(author_id=self.request.user.id, confirm=False).order_by('-deadline')


class TelegramsArchive(LoginRequiredMixin, ListView):
    model = Telegrams
    template_name = 'panel/archive.html'
    paginate_by = 10

    def get_queryset(self):
        return Telegrams.objects.all().filter(author_id=self.request.user.id).order_by('-deadline')


class TelegramDetailView(LoginRequiredMixin, DetailView):
    model = Telegrams

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TelegramDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        tlg = Telegrams.objects.get(id=self.object.get_id())
        context['tlg'] = tlg.executors_set.all()
        return context


class TelegramsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Telegrams
    success_url = "/panel/"

    def test_func(self):
        tlg = self.get_object()
        print(tlg)
        if self.request.user == tlg.author:
            return True
        return False


class TelegramsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Telegrams
    # form_class = AddTelegram
    success_url = "/panel/"
    template_name = "panel/telegrams_update.html"
    fields = ['description', 'deadline', 'tlg_scan', 'tlg_number', 'note', 'confirm', 'priority', ]

    @property
    def get_units_db(self):
        tlg = Telegrams.objects.get(id=self.object.get_id())
        #tlg = get_object_or_404(Telegrams, id=self.object.get_id())
        self.tlg_output = Telegrams.objects.get(id=self.object.get_id())
        tlg_executors = tlg.executors_set.all()
        tlg_exec_list = []
        for i in tlg_executors:
            tlg_exec_list.append(i.unit)
        # print(i.unit)
        return tlg_exec_list

    def test_func(self):
        tlg = self.get_object()
        if self.request.user == tlg.author:
            return True
        return False

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(TelegramsUpdateView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        tlg_exec_list = self.get_units_db

        context['list'] = ['A2326', 'A0355', 'A1214', 'A0501', 'A0536', 'A0693', 'A1302', 'A3283',
                           'A1978', 'A1962', 'A0563', 'A1964', 'A0389', 'A0591', 'A3336', 'A1828', 'A3034', 'A1035', 'A0943',
                           'A1823', 'A0891', 'A2129', 'A3139', 'A3750', 'A1363', 'A1588', 'A1361',
                           'Дн ОТЦК та СП', 'Дон ОТЦК та СП', 'Зп ОТЦК та СП', 'Хар ОТЦК та СП', 'Луг ОТЦК та СП', 'A4226', '64 ПУСЗ та ІС']
        context['ttt'] = tlg_exec_list
        return context

    def form_valid(self, form):
        units_test = self.request.POST.getlist('test1')
        units_db = self.get_units_db
        select_units = self.request.POST.getlist('test')

        # required for checkboxes
        if len(units_test) == 0 and len(select_units) == 0:
            messages.warning(self.request, 'error')
            return redirect('telegram-update', self.object.get_id())
        # delete executors-units from db
        if list(set(units_db).symmetric_difference(set(units_test))):
            print("DELETE")
            print(set(units_db).symmetric_difference(set(units_test)))
            l = list(set(units_db).symmetric_difference(set(units_test)))
            for i in l:
                Executors.objects.filter(telegrams_id=self.object.get_id(), unit=i).delete()

        # add executors-units to db
        if select_units:
            for i in select_units:
                self.tlg_output.executors_set.create(unit=i)
        # section update telegram information

        tlg_scan = form.cleaned_data.get('tlg_scan')

        if tlg_scan != self.tlg_output.tlg_scan:
            print(tlg_scan)
            print(True)
            if os.path.exists(str(self.tlg_output.tlg_scan)):
                os.remove(str(self.tlg_output.tlg_scan))
            form.save()
        form.save()

        return redirect('panel-home')


@login_required()
def CheckUnits(request, pk):

    tlg = Telegrams.objects.get(id=pk)
    ttt = tlg.executors_set.all()
    if request.method == 'POST':
        for i in ttt:
            Executors.objects.filter(telegrams_id=tlg.id, unit=i.unit).update(status=False)
        sss = request.POST

        for i in sss.getlist('test'):
            Executors.objects.filter(telegrams_id=tlg.id, unit=i).update(status=True)
        print(f"Усього тлг --> {len(Executors.objects.filter(telegrams_id=tlg.id).all())}, де виконано --> {len(Executors.objects.filter(telegrams_id=tlg.id, status=True).all())}")
        if len(Executors.objects.filter(telegrams_id=tlg.id).all()) == len(Executors.objects.filter(telegrams_id=tlg.id, status=True).all()):
            print("Всі виконали")
            tlg.confirm = True
            tlg.save()
        else:
            tlg.confirm = False
            tlg.save()
            print("Не всі виконані")
        return redirect('panel-home')

    return render(request, 'panel/telegrams_check.html', {'ttt': ttt, "tlg": tlg})


@login_required
def add_tlg(request):
    if request.method == 'POST':
        form = AddTelegram(request.POST, request.FILES)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)

            description = form.cleaned_data.get('description')
            deadline = form.cleaned_data.get('deadline')
            tlg_scan = form.cleaned_data.get('tlg_scan')
            tlg_number = form.cleaned_data.get('tlg_number')
            note = form.cleaned_data.get('note')
            # confirm = form.cleaned_data.get('confirm')
            priority = form.cleaned_data.get('priority')

            tlg = Telegrams(deadline=deadline, description=description, author=user, tlg_scan=tlg_scan,
                            tlg_number=tlg_number, note=note, priority=priority)
            tlg.save()

            executors = form.cleaned_data.get('executors')
            for i in executors:
                if i != 'ALL':
                    tlg.executors_set.create(unit=i)

            return redirect('panel-home')

    else:
        form = AddTelegram()
    return render(request, 'panel/add_tlg.html', {'form': form})


@login_required()
def pdf_view(request, pk):
    try:

        tlg = Telegrams.objects.get(id=pk)
        return HttpResponse(open(str(tlg.tlg_scan), 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()


@login_required()
def search_by_unit(request, name):
    ex = Executors.objects.filter(unit=name)
    ex_status_true = Executors.objects.filter(unit=name, status=True).count()
    ex_status_false = Executors.objects.filter(unit=name, status=False).count()

    sum_ = ex_status_true + ex_status_false
    return render(request, 'panel/units_detail_tlg.html', {"units": ex, "name": name,
                                                           "ex_status_true": ex_status_true,
                                                           "ex_status_false": ex_status_false,
                                                           "sum_": sum_})


class TelegramsSearchView(FormView):
    template_name = 'panel/search.html'
    model = Telegrams
    form_class = SearchTelegrams
    success_url = "/panel/"

    def get_context_data(self, **kwargs):
        context = super(TelegramsSearchView, self).get_context_data(**kwargs)
        context['search_text'] = self.get_queryset()
        return context

    def get_queryset(self, **kwargs):
        name = self.request.GET.get('search_input', '')
        date_create = self.request.GET.get('date_create', '2021-10-26 - 2021-10-29')
        confirm: object = self.request.GET.get('confirm')
        priority = self.request.GET.get('priority')
        print(confirm)
        
        if not confirm: confirm = 0
       
        def check_dates(input_):

            l = input_.split(" ")

            if l[0] == l[2]:
                d1 = l[0] + " 00:00:01"
                d2 = l[0] + " 23:59:59"
                return [d1, d2]
            else:
                return [l[0], l[2]]

        x = check_dates(date_create)

        return Telegrams.objects.filter(Q(tlg_number__icontains=name) & Q(date_create__range=x) & Q(confirm=confirm) & Q(priority=priority))

telegram_project/panel/templates/panel/add_tlg.html
{% extends 'panel/base.html' %}



{% load crispy_forms_tags %}
{% block content %}

<div class="content-section">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">OK</button>
    </form>


</div>
<script>
$('#id_executors_0').click(function(event) {
    if(this.checked) {
        // Iterate each checkbox
        $(':checkbox').each(function() {
            this.checked = true;
        });
    } else {
        $(':checkbox').each(function() {
            this.checked = false;
        });
    }
});
</script>
<script>
jQuery.datetimepicker.setLocale('uk');
$("#id_deadline").datetimepicker({
format:'Y-m-d H:m',
minDate: 0,
language: 'uk',
locale: 'uk',
allowTimes:[
  '12:00', '13:00', '14:00',
  '15:00', '16:00', '17:00', '18:00', '19:00'
 ]
});


</script>



{% endblock%}

telegram_project/panel/templates/panel/archive.html
{% extends 'panel/base.html' %}
{% block content %}


    <table class="table table-striped">
        <thead class="">
        <tr>

            <th scope="col">Виконати до: </th>
            <th scope="col">Опис телеграми </th>
            <th scope="col">№ вих. телеграми </th>
            <th scope="col">Змінити </th>
        </tr>
        </thead>
        <tbody>
        {% for i in object_list %}
        <tr>

            <td> {{ i.deadline | date:"d.m.Y H:m"}}</td>
            <td> {{ i.description |slice:":71"}}</td>
            <td> {{ i.tlg_number }}</td>

            <td>
                <button class="btn btn-info"><a href="{% url 'telegram-update' i.id %}" style="color:white;"><i class="fas fa-edit"></i></a></button>
                <button class="btn btn-info"><a href="{% url 'check' i.id %}" style="color:white;"><i class="fas fa-check-square"></i></a></button>
                <button class="btn btn-info"><a href="{% url 'telegram-detail' i.id %}" style="color:white;"><i class="fas fa-info-circle"></i></a></button>
                <button class="btn btn-info"><a href="{% url 'telegram-delete' i.id %}" style="color: #c11818d1;"><i class="fas fa-trash"></i></a></button>
            </td>
        {% endfor %}
</tr>
        </tbody>
    </table>
 {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">Перша</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Попередня</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Наступна</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Попередня</a>
      {% endif %}

    {% endif %}

{% endblock%}

telegram_project/panel/templates/panel/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
        <link type="text/css" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script  type="text/javascript" src="{% static 'datetimepicker/jquery.js'  %}"></script>
        <link type="text/css" href="{% static 'datetimepicker/jquery.datetimepicker.min.css' %}" rel="stylesheet" />
        <script  type="text/javascript" src="{% static 'datetimepicker/jquery.datetimepicker.full.js' %}"></script>
        <link type="text/css" href="{% static 'css/fontawesome/all.css' %}" rel="stylesheet" />
        <script  type="text/javascript" src="{% static 'js/moment.min.js'  %}"></script>
        <script  type="text/javascript" src="{% static 'js/daterangepicker.min.js'  %}"></script>
  <link type="text/css" href="{% static 'css/daterangepicker.css' %}" rel="stylesheet" />

</head>
<body>
 {% include "calendarcontrol/menu.html" %}

<div class="container">

    {% block content %} {% endblock%}
</div>

<!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>-->
            <script  type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js'  %}"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->

</body>

</html>

telegram_project/panel/templates/panel/index.html
{% extends 'panel/base.html' %}
{% block content %}


    <table class="table table-striped">
        <thead class="">
        <tr>

            <th class="dateToDo" scope="col">Виконати до: </th>
            <th scope="col">Опис телеграми </th>
            <th scope="col">№ вих. телеграми </th>
            <th scope="col">Змінити </th>
        </tr>
        </thead>
        <tbody>
        {% for i in object_list %}
        <tr>

            <td> {{ i.deadline | date:"d.m.Y H:m"}}</td>
            <td> {{ i.description |slice:":71"}}</td>
            <td> {{ i.tlg_number }}</td>

            <td>
                <button class="btn btn-info"><a href="{% url 'telegram-update' i.id %}" style="color:white;"><i class="fas fa-edit"></i></a></button>
                <button class="btn btn-info"><a href="{% url 'check' i.id %}" style="color:white;"><i class="fas fa-check-square"></i></a></button>
                <button class="btn btn-info"><a href="{% url 'telegram-detail' i.id %}" style="color:white;"><i class="fas fa-info-circle"></i></a></button>
                 <button class="btn btn-info"><a href="{% url 'telegram-delete' i.id %}" style="color: #c11818d1;"><i class="fas fa-trash"></i></a></button>
            </td>
        {% endfor %}
</tr>
        </tbody>
    </table>
 {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">Перша</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Попередня</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Наступна</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Попередня</a>
      {% endif %}

    {% endif %}

{% endblock%}

telegram_project/panel/templates/panel/search.html
{% extends 'panel/base.html' %}



{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{{ x }}
<div class="container">
    <br>
<div class="content-section">
    <form method="GET" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form | crispy}}
        <br>
        <button type="submit" class="btn btn-primary">OK</button>
    </form>


</div>
<br>
    <ul style="list-style-type:none;">

    {% if search_text %}
   <h4> Результат пошуку</h4>
  {% for i in search_text %}


   <li>  <a href="{% url 'telegram-detail' i.id %}" ><i class="fas fa-envelope-open-text"></i>     {{ i.tlg_number }} від {{ i.date_create| date:"d.m.Y"}}</a></li>

    {% endfor %}
    {% else %}
       <div style="text-align: center;">
           <h4 >Результат пошуку не дав</h4>
        <img src="{% static 'images/search_error.png' %}">

           </div>
     {% endif %}
</ul>
</div>
<script>
$('#id_date_create, #id_deadline').daterangepicker({

locale: {
      format: 'YYYY-MM-DD',
       "daysOfWeek": [
            "НД",
            "ПН",
            "ВТ",
            "СР",
            "ЧТ",
            "ПТ",
            "СБ"
        ],
         "monthNames": [
            "Січень",
            "Лютий",
            "Березень",
            "Квітень",
            "Травень",
            "Червень",
            "Липень",
            "Серпень",
            "Вересень",
            "Жовтень",
            "Листопад",
            "Грудень"
        ],
         "firstDay": 1
    }
});

$("#id_priority_0").prop("checked", true);

</script>
{% endblock %}

telegram_project/panel/templates/panel/show_tlg.html
{% extends 'panel/base.html' %}
{% block content %}
<h1>TELEGRAM CONTROL PANEL PAGE!</h1>


{{ telega.description }}
{{ telega.deadline }}
{{ telega.tlg_number}}
{{ telega.priority }}
{% for i in tlg %}

{% if  i.status   %}
   <div> <input type="checkbox" name="{{ i.unit }}" checked>
    <label>{{ i.unit }}</label>
       </div>
{% else %}
    <div> <input type="checkbox" name="{{ i.unit }}" >
    <label >{{ i.unit }}</label>
    </div>
{% endif %}

{% endfor %}




{% endblock%}

telegram_project/panel/templates/panel/telegrams_check.html
{% extends 'panel/base.html' %}
{% block content %}
<br>

<div>
    Відмітьте/зніміть прапорцем напроти підрозділу, який відповів/невідповів на тлг {{  tlg.tlg_number }} від {{ tlg.date_create| date:"d.m.Y" }}
</div>
<hr>
  <i class="fas fa-users"></i> Розрахунок розсилки:
  <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
  {% for i in ttt %}

{% if  i.status   %}
   <div> <input type="checkbox" name="test"  value="{{ i.unit }}" checked>
    <label>{{ i.unit }}</label>
       </div>
{% else %}
    <div> <input type="checkbox" name="test" value="{{ i.unit }}">
    <label >{{ i.unit }}</label>
    </div>
{% endif %}

{% endfor %}

      <br>
  <button type="submit" class="btn btn-primary">OK</button>

  </form>

{% endblock %}

telegram_project/panel/templates/panel/telegrams_update.html
{% extends 'panel/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        СПИСОК ЧАСТИН
<div> <input type="checkbox"  value="all_un"  onClick="toggle(this)">
              <label> Виділити всі </label>
</div>
{% for i in list %}

{% if i in ttt %}

   <div> <input type="checkbox" name="test1"  value="{{ i }}"  checked>
         <label> {{ i }} </label>
   </div>
{% else %}
     <div> <input type="checkbox" name="test"  value="{{ i }}" >
         <label> {{ i }} </label>
   </div>
{% endif %}


{% endfor %}
        <button type="submit" class="btn btn-primary">OK</button>
    </form>
</div>

{% if messages %}
<div class="messages">
    {% for message in messages %}
            {{ message }}
    {% endfor %}
</div>


{% endif %}
<script>
  function toggle(source) {
  checkboxes = document.getElementsByName('test1');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
   checkboxes = document.getElementsByName('test');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
}
</script>
<script>
jQuery.datetimepicker.setLocale('uk');
$("#id_deadline").datetimepicker({

format:'Y-m-d H:m',
minDate: 0,
language: 'uk',
locale: 'uk',
allowTimes:[
  '12:00', '13:00', '14:00',
  '15:00', '16:00', '17:00', '18:00', '19:00'
 ]
});
</script>
{% endblock%}