telegram_project/calendarcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import EventDetailView, pdf_view, EventUpdateView, EventDeleteView

app_name="calendarcontrol"
urlpatterns = [
  path('',  views.index, name='index'),
  path('event/<int:pk>/',EventDetailView.as_view(), name="event-detail"),
  path('pdf_view/<int:pk>/', views.pdf_view, name='pdf-view'),
  path('update/<int:pk>/', EventUpdateView.as_view(), name='event-update'),
  path('delete/<int:pk>/', EventDeleteView.as_view(), name='event-delete'),
  path('test/<int:pk>/', views.test, name='test'),




]

telegram_project/panel/urls.py
from django.conf import settings
from django.urls import path, include
from . import views
from .views import TelegramsListView, TelegramDetailView, TelegramsDeleteView, TelegramsUpdateView, CheckUnits, TelegramsSearchView, TelegramsArchive
urlpatterns = [

    path('', TelegramsListView.as_view(), name="panel-home"),
    path('add_tlg/', views.add_tlg, name='add-tlg'),
    path('telegram/<int:pk>/', TelegramDetailView.as_view(), name='telegram-detail'),
    path('delete/<int:pk>/', TelegramsDeleteView.as_view(), name='telegram-delete'),
    path('update/<int:pk>/', TelegramsUpdateView.as_view(), name='telegram-update'),
    path('check/<int:pk>/', CheckUnits, name='check'),
    #path('pdf_view/<int:pk>/', views.pdf_view,document_root=settings.MEDIA_ROOT,  name='pdf-view'),
    path('unit_detail/<str:name>/', views.search_by_unit, name='unit-detail'),
    path('search/', TelegramsSearchView.as_view(), name='search-telegrams'),
    path('archive/', TelegramsArchive.as_view(), name='archive-telegrams'),

]

telegram_project/telegram_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include("panel.urls")),
    path('control_up/', include('calendarcontrol.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='telegram_project/login.html', redirect_authenticated_user=True), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.index, name='index')

]

handler404 = 'telegram_project.views.error_404_view'
handler403 = 'telegram_project.views.error_403_view'

telegram_project/calendarcontrol/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User

# Create your models here.

class telegramsControl(models.Model):
	priority_ = [('1', 'Висока'), ('0', 'Низька')]
	date = models.CharField(max_length=200,blank=True,verbose_name='Дата виконання:')
	unit_to_report = models.CharField(max_length=100, null=True, verbose_name='Кому доповісти:')
	tlg_number = models.CharField(max_length=100, null=True, verbose_name='Номер вихідної телеграми')
	description = models.TextField(verbose_name= 'Опис телеграми')
	priority = models.CharField(max_length=20, choices=priority_,  verbose_name='Важливість телеграми', default=0)
	tlg_scan = models.FileField(upload_to='tlg_storage', null=True, blank=True,
                                validators=[FileExtensionValidator(allowed_extensions=['pdf'])],
                                verbose_name='Завантажити скан-копію телеграми')
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="author", null=True)
	confirm = models.BooleanField(default=False, verbose_name='Телеграма виконана!')

	def get_absolute_url(self):
		from django.urls import reverse
		return reverse('calendarcontrol:index')

telegram_project/calendarcontrol/forms.py
from django import forms
from django.forms import ModelForm

from .models import telegramsControl

class ModalForm(ModelForm):
    class Meta:
        model = telegramsControl
        fields = ('date', 'unit_to_report','tlg_number','description','priority','tlg_scan')

telegram_project/calendarcontrol/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse_lazy

from .forms import ModalForm
from .models import telegramsControl
from django.views.generic import DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods


# Create your views here.


@login_required
#@require_http_methods(["POST"])
def index(request):
	events = telegramsControl.objects.filter(author_id=request.user.id)
	if request.method == 'POST':
		form=ModalForm(request.POST, request.FILES)
		print(111)
		if form.is_valid():

			form.instance.author_id=request.user.id
			form.save()
			return redirect('calendarcontrol:index')
	else:
		form = ModalForm(request.POST)

	return render(request,"calendarcontrol/calendar.html", {'form':form, 'title':events})


class EventDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
	model = telegramsControl

	def test_func(self):
		if self.get_object().author == self.request.user:
			return True
		return False

@login_required
def test(request, pk):
		if request.method=="POST":
			db = telegramsControl.objects.get(id=pk)

			if (request.POST.getlist('test1')):
				db.confirm = True
				db.save()
			else:
				db.confirm = False
				db.save()

		return HttpResponse("calendarcontrol:index")

class EventUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = telegramsControl
	template_name = "calendarcontrol/telegramscontrol_update.html"
	fields = ('date', 'unit_to_report','tlg_number','description','priority','tlg_scan')

	def test_func(self):
		if self.get_object().author == self.request.user:
			return True
		return False

	def get_success_url(self):
		return reverse_lazy('calendarcontrol:index')

class EventDeleteView(LoginRequiredMixin,UserPassesTestMixin, DeleteView):
	model = telegramsControl
	success_url = "/control_up/"

	def test_func(self):
		if self.get_object().author == self.request.user:
			return True
		return False


@login_required
def pdf_view(request, pk):
    try:
        tlg = telegramsControl.objects.get(id=pk)
        return HttpResponse(open(str(tlg.tlg_scan), 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()

telegram_project/calendarcontrol/templates/calendarcontrol/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    {% load static %}
          <link type="text/css" href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet" />
          <link type="text/css" href="{% static 'css/fontawesome/all.css' %}" rel="stylesheet" />

  </head>
<style>
 body {
font-family: Georgia, serif;
font-style: italic;

}
.fc-day-sat, .fc-day-sun {
    background-color: #FFFFCC;
}
</style>
  {% include "calendarcontrol/menu.html" %}
  <body>
{% block content %}{% endblock %}

  </body>
    <script src="{% static 'js/jquery.min.js' %}"></script>

  <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>

<script type="text/javascript">
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
</script>
</html>

telegram_project/calendarcontrol/templates/calendarcontrol/calendar.html
{% extends 'calendarcontrol/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% block extra_head %}
{% load static %}
    <script  type="text/javascript" src="{% static 'fullcalendar/main.min.js'  %}"></script>
    <link rel="stylesheet" href="{% static 'fullcalendar/main.min.css' %}" type="text/css" />

{% endblock %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Додати контроль на вищій штаб</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        <form action="{% url 'calendarcontrol:index' %}"  method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form | crispy }}
<!--                <input type="text" name="report_to_up">-->
<!--                <input type="text" name="telegram_num">-->
<!--                <input type="file" name="file_tlg">-->
<!--                <input type="text" name="description">-->
         <div id="error"></div>
         <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Відміна</button>
                <button type="submit" class="btn btn-primary">Додати</button>
         </div>
        </form>
      </div>

    </div>
  </div>
</div>
<!-- end Modal -->
<div class="container">
<div id="calendar"></div>
    </div>
<script>
    var calendarEl=document.getElementById("calendar")

var calendar = new FullCalendar.Calendar(calendarEl,{


   locale: 'uk-ua',

   firstDay:1,
   selectable: true,
height: 700,
 aspectRatio: 2,

   events: [
   {% for e in title %}
    {
          id: '{{ e.id }}',
      title: `{{ e.unit_to_report }}`,
      start: '{{ e.date }}',
      description: `{{ e.description }}`
    },
    {% endfor %}
    ],
    eventMouseEnter: function(event, jsEvent, view) {
console.log(event.event.extendedProps.description)
var container=document.getElementsByClassName('fc-event-title-container')
Array.from(container).forEach((e)=>{
e.setAttribute("data-toggle","tooltip")
e.setAttribute("title",event.event.extendedProps.description)

})
},

  dateClick:function(event) {
               console.log(event)
               var modal = $("#exampleModal");
               var id_date=document.getElementById('id_date')
               id_date.value=event.dateStr
               id_date.readOnly=true
                modal.modal('show');
            },
   eventClick: function(e){
   console.log(e.event._def.publicId)
   var id=e.event._def.publicId
       var url = window.location.origin


       window.open(window.location.href+"event/"+parseInt(e.event._def.publicId)+"/","_self")
   }
})


calendar.render()
</script>
{% load static %}
<script  type="text/javascript" src="{% static 'calendarcontrol/calendar.js'  %}"></script>


{% endblock%}

telegram_project/calendarcontrol/templates/calendarcontrol/menu.html
<nav class="navbar navbar-dark bg-primary">
 <a class="navbar-brand" href="{% url 'panel-home' %}" style="margin-left:20px;"> На головну!</a>
    <label style="margin-left: auto; margin-right: 20px; color:white;">Привіт, {{ user }}</label>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">

        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'add-tlg' %}">Додати телеграму</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'search-telegrams'   %}">Пошук телеграм</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'calendarcontrol:index'   %}">Контроль на вищий штаб</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Вийти</a>
        </li>
      </ul>

    </div>
  </div>

</nav>

telegram_project/calendarcontrol/templates/calendarcontrol/telegramscontrol_confirm_delete.html
{% extends 'calendarcontrol/base.html' %}
{% block content %}
<div class="content-section">
    <form method="post">
        {% csrf_token %}
     <fieldset class="form-group">

        <legend class="border-bottom mb-4">Видалити пост?</legend>
       <h2>Ви точно бажаєте видалити телеграму № {{ object.tlg_number }}?</h2>
       <div class="form-group">
         <button class="btn btn-danger" type="submit">Так, згоден</button>
         <a type="button" class="btn btn-info" href="{% url 'index' %}">Ні</a>
       </div>
    </fieldset>

    </form>

</div>


{% endblock%}

telegram_project/calendarcontrol/templates/calendarcontrol/telegramscontrol_detail.html
{% extends 'calendarcontrol/base.html' %}

{% block content %}
{% load static %}
   <link type="text/css" href="{% static 'css/switch_btn.css' %}" rel="stylesheet" />
<a href="{% url 'calendarcontrol:index' %}" type="button" class="btn btn-link">До календарю</a>
<div class="container">
    <div class="row">
        <div class="col-5">
             {% if object.priority == "1" %}
            <i class="fas fa-exclamation fa-1x" style="color:red;"></i>

            {% endif %}
                 <i class="fas fa-envelope-open-text"></i>
              № {{ object.tlg_number}}
        </div>
         <div class="col-3">
              <i class="fas fa-check-double"></i> Статус телеграми:
             {% if object.confirm %}
                виконана!
                {% else %}
                    не виконанa!
                {% endif %}
        </div>
        <div class="col-4">
             <h4> <i class="fas fa-hourglass-half"></i>Виконати до {{ object.date }}</h4>
        </div>
    </div><!-- end row div-->
    <hr>

    <div class="row">
        <div class="col-6">
        <label>Короткий опис телеграми</label>
        <br>
      {{ object.description }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-6">
            {% if object.tlg_scan %}
                Переглянути телеграму
                <a href="{% url 'calendarcontrol:pdf-view' object.pk %}" target="blank" ><i class="far fa-file-pdf fa-2x"></i></a>
            {% else %}
            Телеграму не завантажено!

            {% endif %}

        </div>
    </div>
</div>


<div class="container">
    <hr>
        <div class="row">
            <div class="col-3">
                <label>Відмітка про виконання <i class="fas fa-clipboard-check fa-2x" style="color:#2196F3;"></i></label>
            </div>
            <div class="col-1">

                <form method="post" action="{% url 'calendarcontrol:test' object.id %}" id="fff">
                <label class="switch">

                {% csrf_token %}

                {% if object.confirm %}
                        <input type="checkbox" name="test1" id="test1" checked>
                {% else %}
                        <input type="checkbox" name="test1"  >
                        {% endif %}
                        <span class="slider round"></span>
                    </label>

                </form>
            </div>
            <div class="col-3">
                <a href="{% url 'calendarcontrol:event-update' object.pk %}" class="btn btn-primary">Редагувати</a>
                <a href="{% url 'calendarcontrol:event-delete' object.pk %}" class="btn btn-danger">Видалити</a>

            </div>
        </div>
</div>

<script>
var f=document.getElementById('fff')
var csrf=document.getElementsByName('csrfmiddlewaretoken')

var r=document.getElementsByName('test1')
r[0].addEventListener("change", c=>{
const fd=new FormData()
fd.append('csrfmiddlewaretoken',csrf[0].value)
if (r[0].checked == true ){
fd.append('test1',r[0].value)
}

 $.ajax({
    type:'post',
    url:"{% url 'calendarcontrol:test' object.id %}",
    data:fd,
    cache : false,
    contentType: false,
    processData: false,
    success:function(e){
    location.reload();
    }

    })
})


</script>

{% endblock %}

telegram_project/calendarcontrol/templates/calendarcontrol/telegramscontrol_update.html
{% extends 'calendarcontrol/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="container">
<a href="{% url 'calendarcontrol:index' %}" type="button" class="btn btn-link">До календарю</a>
<form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        {{ form | crispy }}
     <button type="submit" class="btn btn-primary">OK</button>
</form>
    </div>
<hr>
<script>
    document.getElementById('id_date').type='date'
</script>
{% endblock %}